### ISSUE TITLE
Move from .JS files to standard JSON files for artifact file templates

### ISSUE THREAD

**Issue by einari** [dolittle-obsolete/cli#16]
Instead of a `.JS` file - we should just have a standard JSON file. 

In addition, take away the underscore prefix [_template.js](https://github.com/dolittle-boilerplates/ArtifactTemplates/blob/master/Content/CSharp/Command/_template.js). File should just be called `template.json`.

**Comment by woksin** [comment]
Keep the same key-value pairs and naming?

**Comment by einari** [comment]
Just added more details on the #8 issue
