### ISSUE TITLE
Add support for options from the boilerplate that can be optionals in the CLI tool

### ISSUE THREAD

**Issue by einari** [dolittle-obsolete/cli#30]
Typically we need options to have the following structure:

```json
{
   "options": [
      {
           "description":"the description of the option",
           "name": "the name of the option",
           "shortName": "the short name of the option"
      }
   ]
}
```

Example of this is 
`dolittle add command <name> --namespace <some.namespace>`

The --namespace is the optional coming from the artifact-template, which is coming from the `name` property. The shortName of this could be `-n`:

`dolittle add command <name> -n <some.namespace>`

All options should just be added to the `context` object

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1121163669470831)

**Comment by woksin** [comment]
I think I'll park this for a while. "args" is not very supportive when it comes to options apparently ...
