### ISSUE TITLE
Not detecting changes to the dolittle files

### ISSUE THREAD

**Issue by smithmx** [dolittle-obsolete/cli#48]
There seems to be an issue with caching or suchlike in the build tool.

When manually editing the artifacts.json file, etc. (e.g. renaming the type or namespace) then the tool seems to remember the previous artifacts and generates the migration warning.  Even deleting the file still generates the warning.

Restarting the IDE fixes the issue.

Kai has experienced this on Windows / Visual Studio.

**Comment by woksin** [comment]
The cli does not know of or care about the artifacts.json or topology.json files at all. So this os probably a DotNET Build Tool specific thing
