### ISSUE TITLE
Introduce a way to extend the CLI tool with plugins

### ISSUE THREAD

**Issue by einari** [dolittle-obsolete/cli#58]
Concrete example; we want to be able to support Veracity and creating bounded contexts that are configured to work directly with Veracity. This should not be something developed directly in the tool itself - but rather be in its own repository and deployed on its own to NPM and discovered automatically by the tool.

Discovery mechanism needs to be figured out. But the idea is to have all capabilities available - meaning that the entrypoint of the tool will know about everything and have discovered all plugins - but not necessarily install it until its used. 

This would make it very transparent for the developer.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1121163666496839)

**Comment by woksin** [comment]
The CLI tool with version 5.0 is expandable by boilerplates, not plugins, but I assume that's the intention of this issue, @einari
