### ISSUE TITLE
Separate the CLI interaction layer from what the tool is doing

### ISSUE THREAD

**Issue by einari** [dolittle-obsolete/cli#59]
The set of tools that the CLI exposes are not CLI specific - in fact they can be used by a variety of tools, like plugins to code editors and in Dolittle Studio itself for instance. Instead of going through the CLI interaction layer, we could go through the API surface directly. 

Separate into two different packages - the actual tool and the facade that gives you the CLI interface. 

This needs to be looked at in conjunction with #58 - since extensibility is something we'd like for the underlying toolset as a whole as well.

**Comment by einari** [comment]
There is now a new repository called [Common](https://github.com/dolittle-tools/common) that can hold the common functionality. 

Typically the [VSCode repository](https://github.com/dolittle-tools/vscode) can then use this and the CLI as two different interaction points.

**Comment by woksin** [comment]
What do you mean with 'CLI interaction layer'? The inquierer.js stuff?

**Comment by einari** [comment]
All the things that represent dealing with CLI arguments, messages and inquiring which is CLI specific, makes up the CLI interaction layer. This should be kept here - while all reusable - non CLI things should be out in the common thing. Package could be named "@dolittle/common-tools" or something to that effect - as just common doesn't say anything. It's fine for the repo to be called common, as it exists in the tooling org.
