### ISSUE TITLE
Add support for tags on boiler plates

### ISSUE THREAD

**Issue by einari** [dolittle-obsolete/cli#61]
The boilerplates manager should support the ability to get boilerplates by tags.

Notice the `tags` property in the JSON example for the `boilerplate.json`file below:

```json
{
    "name": "Veracity Bounded Context Adornment",
    "language": "csharp",
    "type": "boundedContext-adornment",
    "parent": "https://github.com/dolittle-boilerplates/CSharp.BoundedContext",
    "tags": ["veracity"],
    "description": "This is an adornment to a bounded context"
 }
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1121163561492895)

**Comment by woksin** [comment]
This belongs to the 'common' project
