### ISSUE TITLE
Add support for post steps that gets run - boiler plate specific

### ISSUE THREAD

**Issue by einari** [dolittle-obsolete/cli#62]
Boilerplate system should support spawning a post create script to do things that is needed after a creation.

For instance for a C# boilerplate; run `dotnet restore` in the correct project.

For a boilerplate that holds node things; run `yarn`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1121163560786472)

**Comment by einari** [comment]
Note: remove the Webpack dependency in the core CLI - this should be something the specific boilerplate defines as a dependency, since it will be the one to actually do this

**Comment by woksin** [comment]
This is a 'common' project issue
