### ISSUE TITLE
We need to be clear on our dependencies and have clear errors if they're not there

### ISSUE THREAD

**Issue by einari** [dolittle-obsolete/cli#85]
- [ ] Git 
- [ ] Docker
- [ ] WebPack

We need to point to documentation for how to install the different things.

Even better, if we can not have dependencies on other CLI tools - WebPack is an example of this.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1121163520680869)

**Comment by jakhog** [comment]
The Git dependency should be gone now...

**Comment by woksin** [comment]
This is a common-tooling concern, not just cli
