### ISSUE TITLE
Add post creation script support

### ISSUE THREAD

**Issue by einari** [dolittle-obsolete/cli#9]
For instance when creating a new bounded context, we want to run "npm install/yarn", dotnet restore and maybe even dotnet build.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1121163694153826)

**Comment by woksin** [comment]
Can you give a more thorough explanation, @einari?

I did not quite comprehend the task

**Comment by einari** [comment]
Typically in the JS file describing the boilerplate, we should have a scripts option. Which is basically CLI commands we will spawn. 

Much like how NPM does its [Scripts](https://docs.npmjs.com/misc/scripts).

For instance if we take the [CSharp BoundedContext boilerplate definition](https://github.com/dolittle-boilerplates/CSharp.BoundedContext/blob/master/boilerplate.js): 

```javascript
module.exports = {
    name: 'Basic template',
    language: 'csharp',
    type: 'boundedContext',
    description: 'This is a basic boilerplate',
    'scripts': [
        'dotnet restore',
        'dotnet build --no-restore'
    ]
};
```

**Comment by woksin** [comment]
This belongs to the 'common' project
