### ISSUE TITLE
The CLI is for many developers the portal into working with Dolittle, it has to look nice and provide a pleasant  experience

### ISSUE THREAD

**Issue by woksin** [dolittle-obsolete/cli#92]
Look at other CLI tools for inspiration.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1121163252304122)

**Comment by einari** [comment]
Sindre Wilting ( https://app.asana.com/0/1116545856664150/list ) - could you guys sync on wether or not we keep this issue and maybe make this more concrete.

**Comment by einari** [comment]
➤ Sindre Wilting commented:

I think that this should be split up into concrete tasks later on
