### ISSUE TITLE
It's time to switch up CLI framework

### ISSUE THREAD

**Issue by woksin** [dolittle-obsolete/cli#93]
child of #92

* Vorpal
* Oclif
* Caporal
* CommanderJs

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1121163289642133)

**Comment by woksin** [comment]
Another way to go around is to use a simple args parser package, like minimist. 
None of the cli frameworks I've seen provieds the flexibility and extensibility that I would like to have

**Comment by einari** [comment]
➤ Pavneet Singh Saund commented:

What is this? 🙂

**Comment by einari** [comment]
➤ Pavneet Singh Saund commented:

Oh, just saw the link to The CLI is for many developers the portal into working with Dolittle, it has to look nice and provide a pleasant  experience ( https://app.asana.com/0/1115616103797671/1121163252304122 ). Can follow up context there.

**Comment by einari** [comment]
➤ Sindre Wilting commented:

Yeah, we just synced with the tooling repos😊
This particular task can be marked as done, since the new Cli strategy has already been implemented without any CLI framework

**Comment by einari** [comment]
➤ Sindre Wilting commented:

I need to do some cleanup
